import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import Map from '@/components/map';

export default function Home() {
    return (
        <>
            <Head>
                <title>Bitcamp: Housing</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
              
               <div className={styles.grid}>
                <div>
                <Map></Map>
                </div>
                <div>
                <Map></Map>
                </div>
                </div>


            </main>
        </>
    );
}
